### ISSUE TITLE
Desafío aceptado 😎

### ISSUE THREAD

**Issue by ThomasMiz** [j0liu/POP3-Server#1]
Dado su reciente [desafío](https://github.com/ThomasMiz/mail-devil/issues/1), el día de hoy me tomé el trabajo de analizar el performance de su TP contra mi implementación.

La métrica en cuestión es la más pedorra que se me pudo ocurrir; `NOOP`s por segundo. Realicé un análisis de throughput de `NOOP`s para ambos servidores en condiciones idénticas, para distintas cantidades de clientes.

Dado que su TP solo soporta hasta 10 clientes (esto no está mal, es como lo pedía la consigna) probé entre 1 a 10 clientes, abriendo dicha cantidad de clientes y midiendo cuanto tiempo tarda en terminar que todos los clientes tiren un millón de `NOOP`s y que vuelvan todos los `+OK`. Corrí todo dos veces, tomando el peor caso para mi servidor y el mejor caso de su servidor.

Estos son los resultados:
![Figure_1](https://github.com/user-attachments/assets/7d62267d-340a-4d14-9fb5-a9bf661b7f5a)

Como se puede observar en este gráfico, la destrucción es total.

Algunos comentarios adicionales:
- Su buffer size por defecto es 8K. Muy buena elección, yo elegí lo mismo. Igual no hice pruebas ni nada para elegirlo.
- Correcta implementación de pipelining. No solo pueden ejecutar correctamente varios comandos mandados recibidos todos juntos, sinó que si el cliente cierra su parte de escritura (para indicar que no va a enviar nada más) ustedes correctamente terminan de ejecutar los comandos restantes hasta que el read indique end of file, y recién ahí cierran la conexión.
- Puede ser que el degradamiento de performance en este test se deba a no bufferear las respuestas, realizando una syscall de `send` por cada respuesta. Yo parseo todos los comandos que pueda hasta que se llene el buffer de salida, y recién ahí hago write al socket. Por eso el tiempo de ejecución casi no cambia con la cantidad de clientes.

Para cerrar: cabe aclarar que esta métrica de throughput es totalmente papanata y no muy representativa del mundo real. El bottleneck principal de un servidor POP3 en casos de uso típicos estará en el copiado de archivos (hablando antes de la red y el disco).

Muy buen laburo!

**Comment by david-wis** [comment]
Nanana que es eso del NOOP, haceme las mismas pruebas que hizo Coda. Pone un archivo pesado y veamos si llegás a la misma velocidad.

**Comment by ThomasMiz** [comment]
> Nanana que es eso del NOOP, haceme las mismas pruebas que hizo Coda. Pone un archivo pesado y veamos si llegás a la misma velocidad.

Ustedes no realizan conversión de fines de línea, por ende no respetan el RFC. Automáticamente gano yo 😎

**Comment by david-wis** [comment]
Si recurris a ese argumento es que ya lo probaste y somos más rápidos (?) 
Además, si dovecot puede hacerlo, nosotros también.

**Comment by ThomasMiz** [comment]
> Si recurris a ese argumento es que ya lo probaste y somos más rápidos (?) Además, si dovecot puede hacerlo, nosotros también.

No lo había probado, pero lo discutimos el otro día y ustedes me comentaron que no convierten fines de línea. Como no hacen ese procesamiento (que, otra vez, pide el RFC), el CPU no tiene que recorrer y modificar el buffer y por ende era esperable que yo tenga **mucho** menos throughput.

Efectivamente, ahí lo probé con un archivo de 2.44GBs (una sola descarga para cada uno) y su servidor tardó alrededor de la mitad de tiempo en terminar la descarga 🥇

> Además, si dovecot puede hacerlo, nosotros también.

Además, si Alberto Fernandez puede hacerlo, nosotros también.

**Comment by ThomasMiz** [comment]
### He vuelto!

Me quedé pensando sobre esto y llegué a la conclusión de que mi argumento no tiene sentido. Yo dije que:

> el CPU no tiene que recorrer y modificar el buffer y por ende era esperable que yo tenga mucho menos throughput.

Pero esto es falso, porque ustedes también tienen que recorrer el buffer para aplicar byte stuffing! Así que me puse a revisar mi código y buscar qué optimizar. No se me ocurría buscar qué más cambiar así que revisé su código a ver cuál era su ingrediente secreto para semejante velocidad.

# Tramposos!
Totalmente tramposos. Yo estaba usando buffers de 8K, como veía que tenían en la configuración ustedes, para que la competencia sea justa. Sin embargo, en [la línea 598 del archivo pop3.c](https://github.com/j0liu/POP3-Server/blob/main/src/pop3.c#L598C1-L598C26) encuentro lo siguiente:
```c
#define BUFFER_SIZE 65536
```

Están usando buffers de 64K para el copiado!!!

(esto está perfecto, no es trampa. Yo simplemente creía que usaban de 8K entonces no iba a agrandar mis buffers para que sea justo. Con buffers 8 veces más grandes obviamente me van a ganar)

Con esto en mente, agregué unas optimizaciones más a mi código para aprovechar mejor estos buffers más grandes y los resultados de 5 corridas seguidas son...

![image](https://github.com/user-attachments/assets/20eb6606-8cfe-40f4-b202-b9e9b8b3eadb)

_Nota para la reproducibilidad de los tests: los archivos descargados pueden no coincidir, ya que mail-devil convierte fines de línea mientras POP3-Server agrega un fin de línea adicional al final del archivo._

Ahora sí 😎🤝😎

# Notas adicionales
Este cuatrimestre decidí participar en la corrección de los TPs de protos (por esto es que siquiera decidí hacer [mail-devil](https://github.com/ThomasMiz/mail-devil/), quería aprender el protocolo de entender cómo se implementa. O sea, no puedo corregir un trabajo que no entiendo). Los coloquios fueron este martes y yo usé su servidor para armar pruebas, y probar que las pruebas que armé tengan sentido y funcionen bien.

Talvez será que ustedes me dejaron la vara muy alta, pero ninguno de los TPs me dió la misma primera impresión. A todos les faltaba algo importante como pipelining o byte stuffing, y la mayoría (si no todos) crashearon durante el coloquio (esto es lo que los pros llaman un _SEGV + Core dumped_).

Me hace apreciar el nivel de esfuerzo que va en cada uno de estos trabajos, así que una vez más los felicito por su buen laburo.

Por más que empatemos en velocidad de descarga de archivo, les recuerdo amablemente que mi servidor sigue siendo más rápido con los NOOPs.

Saludos
